In [3]:
#Create a numpy array starting from 2 till 50 with a stepsize of 3.
import numpy as np

arr=np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [1]:
#Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

#Accept two lists of 5 elements each from the user.
list1=[]
numbers1=int(input("enter the length"))
print("enter the five numbers")

for i in range(numbers1):
    data=int(input())
    list1.append(data)
print(list1)

list2=[]
numbers2=int(input("enter the length"))
print("enter the  five numbers")

for i in range(numbers2):
    data=int(input())
    list2.append(data)
print(list2)

enter the length5
enter the five numbers
2 
4
6
5
7
[2, 4, 6, 5, 7]
enter the length5
enter the  five numbers
8
9
3
5
6
[8, 9, 3, 5, 6]


In [6]:
# Convert them to numpy arrays.
n1=np.array(list1)
n2=np.array(list2)
print(n1)
print(n2)


[2 4 6 5 7]
[8 9 3 5 6]


In [8]:
arr=np.concatenate((n1,n2))  
arr

array([2, 4, 6, 5, 7, 8, 9, 3, 5, 6])

In [9]:
arr.sort()
arr

array([2, 3, 4, 5, 5, 6, 6, 7, 8, 9])

In [29]:
#Write a code snippet to find the dimensions of a ndarray and its size.
#dimensions of a ndarray
arr=np.array([2,3,4,5,6])
print("The dimension of 1D array :",arr.shape)

arr2D = np.array([[1,3,4,5], [4,5,6,77], [40,50,88,99]])

print("\n",arr2D)
print("\nThe dimension of 2D array :",arr2D.shape)


The dimension of 1D array : (5,)

 [[ 1  3  4  5]
 [ 4  5  6 77]
 [40 50 88 99]]

The dimension of 2D array : (3, 4)


1

In [11]:
#size
arr2D = np.array([[1,3,4,5], [4,5,6,77], [40,50,88,99]])
print('Total Number of elements in 2D Numpy array : ', np.size(arr2D))

Total Number of elements in 2D Numpy array :  12


In [36]:
#How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
#Hint: np.newaxis, np.expand_dims
a=np.array([5,6])
a.shape



(2,)

In [37]:
b=np.expand_dims(a, axis=0)
print(b)
print(b.shape)

[[5 6]]
(1, 2)


In [38]:
b=np.expand_dims(a, axis=1)
print(b)
print(b.shape)

[[5]
 [6]]
(2, 1)


In [40]:
#Consider two square numpy arrays. Stack them vertically and horizontally.
#Hint: Use vstack(), hstack()

n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [45]:
#How to get unique items and counts of unique items?
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4],[2,3,4]])
np.unique(a, axis=0)


array([[1, 0, 0],
       [2, 3, 4]])

In [52]:
np.unique (a, return_counts=False)

array([0, 1, 2, 3, 4])